### ISSUE TITLE
Some curiosity about the training process

### ISSUE THREAD

**Issue by Wuziyi616** [catta202000/PointNetVlad-Pytorch#1]
Hi, I'm a pytorch user and I'm really grateful that you open source this great work. However, I have some questions about the code. My question is, what are these two global variables HARD_NEGATIVES and TRAINING_LATENT_VECTORS in train_pointnetvlad.py? I notice that in the training process, before epoch 5, they won't be used since they are all empty. But after epoch 5 you will generate some latent_vectors via get_latent_vectors. So I wonder if they're something that help the model converge better, since according to its name (HARD_NAGATIVES), I guess you just select some harder negative samples from the training set. In other words, in the early stage of the training process, you just randomly select samples to train, and then after epoch 5 you select the most difficult samples to train the model more efficiently. Am I correct?

**Comment by cattaneod** [comment]
Hi,
Yes your intuition is correct, and the latent vector are updated every 1400 iterations.
Since this part was taken from the original Tensorflow implementation, please refer to the original paper for more details.

**Comment by Wuziyi616** [comment]
Thank you for your kind answer!
