### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by pareespathak** [catta202000/PointNetVlad-Pytorch#4]
line 361, in process_data
    ob[i] = torch.roll(ob[i], seed, dims=1)
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

Can you suggest why is this error is occurring?

**Comment by cattaneod** [comment]
That line is not part of my code, I can't help you without more information.

**Comment by pareespathak** [comment]
okay, Thank you for your time
