### ISSUE TITLE
Why is batchsize=44 and how can I modify batchsize to be smaller? If you could answer me, I would greatly appreciate it

### ISSUE THREAD

**Issue by lkf263** [catta202000/PointNetVlad-Pytorch#8]
Why is batchsize=44 and how can I modify batchsize to be smaller? If you could answer me, I would greatly appreciate it

**Comment by cattaneod** [comment]
The batch size depends on the parameters in config.py at lines 13-15

https://github.com/cattaneod/PointNetVlad-Pytorch/blob/ff00ff07b17f35db9ddaea15d04c94b491051d4d/config.py#L13-L15

**Comment by lkf263** [comment]
Thank you for your reply. Wishing you a pleasant life and smooth work！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cattaneod/PointNetVlad-Pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月25日(星期一) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cattaneod/PointNetVlad-Pytorch] Why is batchsize=44 and how can I modify batchsize to be smaller? If you could answer me, I would greatly appreciate it (Issue #8)





 
The batch size depends on the parameters in config.py at lines 13-15
 
https://github.com/cattaneod/PointNetVlad-Pytorch/blob/ff00ff07b17f35db9ddaea15d04c94b491051d4d/config.py#L13-L15
